// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "ContactCta" section.

import React from 'react';
import Button from "@/components/ui/Button";

export default function ContactCtaSection(): React.JSX.Element {
  return (
    <div data-webild-section="ContactCta">
      <section aria-label="Kapanış" className="w-full bg-white border-t border-gray-200 py-16 md:py-20">
        <div className="w-content-width mx-auto flex flex-col items-center text-center px-4">
          <h2 className="font-serif text-[28px] sm:text-[36px] font-semibold text-foreground text-balance leading-snug">
            Markanız için bir tasarım sistemi kuralım.
          </h2>
          <div className="mt-8 w-full sm:w-auto">
            <Button text="Projenizi anlatın" href="/contact" variant="primary" className="w-full sm:w-auto text-center justify-center" />
          </div>
        </div>
      </section>
    </div>
  );
}
