// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from '@/components/ui/SectionErrorBoundary';

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
            <SectionErrorBoundary name="about">
              <AboutTextSplit
                title="Hakkımda"
                descriptions={[
                  "Yasemin Günhan olarak, markaların sadece görsel değil, işlevsel ve stratejik bir sisteme sahip olmaları gerektiğine inanıyorum. Tasarım yaklaşımım; derin analiz, estetik disiplin ve modern teknolojilerin sentezidir.",              "Amacım, karmaşık marka hikâyelerini yalın ve etkileyici bir görsel dile dönüştürerek, markanızın hedef kitlesiyle kalıcı bağlar kurmasını sağlamaktır."
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
