/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";

const descriptions = [
  "Ben Yasemin Günhan, marka ve ambalaj tasarımcısıyım. Logo tek başına marka değildir. Renk, yazı, dil ve ambalaj aynı sistemin parçaları olarak çalıştığında marka tutarlı görünür ve hatırlanır.",
  "İsimlendirmeden marka rehberine kadar bütün kimliği tek elden kuruyorum. Bir fintech girişimi için isim, logo, renk ve yazı sistemi ile marka rehberini baştan sona ben tasarladım.",
  "Bir markanın bulunabilmesini de tasarımın parçası sayıyorum."
];

interface HakkımdaTextSplitProps {
  title: string;
  descriptions: string[];
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const HakkımdaInline = () => {
  return (
    <section aria-label="Hakkımda section" className="py-20">
      <div className="flex flex-col gap-20 mx-auto w-content-width">
        <div className="flex flex-col md:flex-row gap-3 md:gap-15">
          <div className="w-full md:w-1/2">
            <TextAnimation
              text={"Markayı sistem olarak kuruyorum."}
              variant={"fade-blur"}
              gradientText={true}
              tag="h2"
              className="text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-balance"
            />
          </div>

          <div className="flex flex-col gap-2 w-full md:w-1/2">
            {descriptions.map((desc, index) => (
              <TextAnimation
                key={index}
                text={desc}
                variant={"fade-blur"}
                gradientText={false}
                tag="p"
                className="text-xl md:text-2xl leading-snug text-balance"
              />
            ))}

            {(undefined || undefined) && (
              <div className="flex flex-wrap gap-3 mt-2 md:mt-3">
                {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
                {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
              </div>
            )}
          </div>
        </div>

        <div className="w-full border-b border-foreground/5" />
      </div>
    </section>
  );
};

export default function HakkımdaSection() {
  return (
    <div data-webild-section="about" data-section="about" id="about">
      <HakkımdaInline />
    </div>
  );
}
