// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from '@/components/ui/SectionErrorBoundary';

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
            <SectionErrorBoundary name="about">
              <AboutTextSplit
                title="Markayı sistem olarak kuruyorum."
                badge="Yasemin Günhan"
                descriptions={[
                  "Ben Yasemin Günhan, marka ve ambalaj tasarımcısıyım. Logo tek başına marka değildir. Renk, yazı, dil ve ambalaj aynı sistemin parçaları olarak çalıştığında marka tutarlı görünür ve hatırlanır.",
                  "İsimlendirmeden marka rehberine kadar bütün kimliği tek elden kuruyorum. Bir fintech girişimi için isim, logo, renk ve yazı sistemi ile marka rehberini baştan sona ben tasarladım.",
                  "Bir markanın bulunabilmesini de tasarımın parçası sayıyorum."
                ]}
                image="https://storage.googleapis.com/webild/users/user_3KFFa5W6OG5DQ11YaXgrbTF1V4I/uploaded-1791230325347-mgsocr89.jpg"
                imageUrl="https://storage.googleapis.com/webild/users/user_3KFFa5W6OG5DQ11YaXgrbTF1V4I/uploaded-1791230325347-mgsocr89.jpg"
                imageSrc="https://storage.googleapis.com/webild/users/user_3KFFa5W6OG5DQ11YaXgrbTF1V4I/uploaded-1791230325347-mgsocr89.jpg"
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
