// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from '@/components/ui/SectionErrorBoundary';

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="İletişim"
                text="Markanızın sistemini tasarlamaya başlayalım. Projenizi anlatın, birlikte neler yapabileceğimizi planlayalım."
                primaryButton={{ text: "info@yasemingunhan.com", href: "mailto:info@yasemingunhan.com" }}
                secondaryButton={{ text: "LinkedIn Profili", href: "https://www.linkedin.com/in/yasemin-gunhan-72bb55172/" }}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
