/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "info@yasemingunhan.com",
  href: "mailto:info@yasemingunhan.com"
};
const secondaryButton = {
  text: "LinkedIn Profili",
  href: "https://www.linkedin.com/in/yasemin-gunhan-72bb55172/"
};

const ContactInline = () => {
  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="slide-up">
          <div className="flex flex-col items-center gap-8 py-12 px-6 md:px-12 rounded card max-w-3xl mx-auto">
            <div className="flex flex-col items-center gap-2 text-center">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit text-foreground">
                <p>{"Schedule Your Free Consultation"}</p>
              </div>

              <TextAnimation
                text={"Markanızın sistemini tasarlamaya başlayalım. Projenizi anlatın; 24 saat içinde dönüş yapalım."}
                variant={"fade-blur"}
                gradientText={true}
                tag="h2"
                className="text-3xl md:text-4xl font-semibold text-center text-balance"
              />
            </div>

            <form onSubmit={(e) => e.preventDefault()} className="w-full flex flex-col gap-6 text-left mt-2">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="flex flex-col gap-1.5">
                  <label htmlFor="contact-name" className="text-sm font-medium text-foreground">
                    Ad Soyad
                  </label>
                  <input
                    id="contact-name"
                    type="text"
                    required
                    placeholder="ör. Yasemin Günhan"
                    className="w-full px-4 py-2.5 rounded border border-foreground/20 bg-background text-foreground text-sm placeholder:text-foreground/40 focus:outline-none focus:border-foreground/60 transition"
                  />
                  <span className="text-xs text-foreground/60">
                    Sizinle doğru şekilde iletişim kurabilmemiz için adınızı belirtin.
                  </span>
                </div>

                <div className="flex flex-col gap-1.5">
                  <label htmlFor="contact-email" className="text-sm font-medium text-foreground">
                    E-posta Adresi
                  </label>
                  <input
                    id="contact-email"
                    type="email"
                    required
                    placeholder="ör. yasemin@sirketiniz.com"
                    className="w-full px-4 py-2.5 rounded border border-foreground/20 bg-background text-foreground text-sm placeholder:text-foreground/40 focus:outline-none focus:border-foreground/60 transition"
                  />
                  <span className="text-xs text-foreground/60">
                    24 saat içinde dönüş ve detaylı teklif bu adrese iletilecektir.
                  </span>
                </div>
              </div>

              <div className="flex flex-col gap-1.5">
                <label htmlFor="contact-service" className="text-sm font-medium text-foreground">
                  İlgilendiğiniz Hizmet / Konu
                </label>
                <input
                  id="contact-service"
                  type="text"
                  placeholder="ör. Marka Kimliği Tasarımı, Web Sitesi veya Tasarım Sistemleri"
                  className="w-full px-4 py-2.5 rounded border border-foreground/20 bg-background text-foreground text-sm placeholder:text-foreground/40 focus:outline-none focus:border-foreground/60 transition"
                />
                <span className="text-xs text-foreground/60">
                  Hangi alanda desteğe ihtiyacınız olduğunu belirtmeniz süreci hızlandırır.
                </span>
              </div>

              <div className="flex flex-col gap-1.5">
                <label htmlFor="contact-message" className="text-sm font-medium text-foreground">
                  Proje Detayları
                </label>
                <textarea
                  id="contact-message"
                  rows={4}
                  required
                  placeholder="Projenizin hedefleri, mevcut durumu ve hedeflenen teslim tarihi gibi detayları kısaca paylaşın..."
                  className="w-full px-4 py-2.5 rounded border border-foreground/20 bg-background text-foreground text-sm placeholder:text-foreground/40 focus:outline-none focus:border-foreground/60 transition resize-none"
                />
                <span className="text-xs text-foreground/60">
                  Ne kadar detay verirseniz, ilk dönüşümüzde o kadar net bir yol haritası sunabiliriz.
                </span>
              </div>

              <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-2 border-t border-foreground/10 mt-2">
                <span className="text-xs text-foreground/70">
                  ⚡ 24 saat içinde e-posta ile dönüş garantisi
                </span>
                <button type="submit" className="primary-button px-6 py-2.5 rounded text-sm font-medium cursor-pointer">
                  Schedule Your Free Consultation
                </button>
              </div>
            </form>

            <div className="flex flex-wrap justify-center gap-3 pt-4">
              <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
              <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" animationDelay={0.1} />
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
