// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlayMarquee from '@/components/sections/hero/HeroOverlayMarquee';
import SectionErrorBoundary from '@/components/ui/SectionErrorBoundary';
import { Zap, Target, Palette, Search } from 'lucide-react';

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
            <SectionErrorBoundary name="hero">
              <HeroOverlayMarquee
                tag="Marka Tasarımı & AEO"
                title="Markanı bir sistem olarak tasarlıyorum."
                description="Adana merkezli tasarım stüdyosu. Stratejik marka kimliği, ambalaj tasarımı ve yapay zekâ destekli arama görünürlüğü (AEO) çözümleri ile markanızı geleceğe hazırlıyorum."
                primaryButton={{ text: "Çalışmalara bak", href: "#projects" }}
                secondaryButton={{ text: "Projeni anlat", href: "#contact" }}
                imageSrc="http://img.b2bpic.net/free-photo/modern-office-desk-composition_23-2147915838.jpg"
                textAnimation="fade-blur"
                items={[
                  { text: "Strateji", icon: Target },
                  { text: "Tasarım", icon: Palette },
                  { text: "Görünürlük", icon: Search },
                  { text: "Hız", icon: Zap }
                ]}
              />
            </SectionErrorBoundary>
          </div>
  );
}
