/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Target, Palette, Search, Zap } from 'lucide-react';
import type { LucideIcon } from "lucide-react";

import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Çalışmalara bak",
  href: "#projects"
};
const secondaryButton = {
  text: "Projeni anlat",
  href: "#contact"
};

const HeroInline = () => {
  return (
    <section
      aria-label="Hero section"
      className="relative overflow-hidden flex flex-col justify-center min-h-[80vh] py-20 md:py-28 bg-[#0F3D3E] w-full"
    >
      <div 
        className="absolute inset-0 z-0 bg-cover bg-center opacity-60"
        style={{ backgroundImage: "url('/hero-arka-plan.png')" }}
      />
      <div className="absolute inset-0 z-0 bg-gradient-to-r from-[#0F3D3E]/90 via-[#0F3D3E]/70 to-transparent" />

      <div className="relative z-10 mx-auto w-content-width">
        <div className="flex flex-col gap-6 max-w-[620px]">
          <h1 className="text-[36px] sm:text-[48px] md:text-[56px] lg:text-[72px] font-semibold leading-[1.05] text-white tracking-tight">
            Markanız önce tasarlanır,<br />
            sonra bulunur.
          </h1>

          <p className="text-[18px] sm:text-[20px] font-normal leading-relaxed text-white/90 max-w-[560px]">
            Adana merkezli marka tasarımcısı Yasemin Günhan. Marka kimliği ve ambalaj tasarlıyorum, ek olarak yapay zekâ destekli arama görünürlüğü kuruyorum.
          </p>

          <div className="flex items-center gap-6 mt-2">
            <a
              href={primaryButton.href}
              className="inline-flex items-center justify-center px-6 py-3 rounded-md bg-[#E4572E] text-white text-[16px] font-semibold hover:bg-[#d04a23] transition-colors"
            >
              {primaryButton.text}
            </a>
            <a
              href={secondaryButton.href}
              className="text-white text-[16px] font-medium underline underline-offset-4 hover:text-white/80 transition-colors"
            >
              {secondaryButton.text}
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
