// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "projects" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from '@/components/ui/SectionErrorBoundary';

export default function ProjectsSection(): React.JSX.Element {
  return (
    <div id="projects" data-section="projects">
            <SectionErrorBoundary name="projects">
              <FeaturesRevealCardsBento
                tag="Projeler"
                title="Seçilmiş Çalışmalar"
                description="Markaların dünyasına dair stratejik ve estetik çıktılar."
                items={[
                  { title: "Günhan Marine", description: "Denizcilik sektörüne yönelik stratejik marka kimliği.", href: "#", imageSrc: "https://storage.googleapis.com/webild/users/user_3KFFa5W6OG5DQ11YaXgrbTF1V4I/uploaded-1791229381381-exwwdmsr.jpg" },
                  { title: "Vira Blacksea", description: "Modern ve minimalist deniz ürünleri ambalaj tasarımı.", href: "#", imageSrc: "https://storage.googleapis.com/webild/users/user_3KFFa5W6OG5DQ11YaXgrbTF1V4I/uploaded-1791229346384-sod75vac.png" },
                  { title: "Alesta Marine", description: "Sektörel dijital görünürlük ve web tasarımı.", href: "#", imageSrc: "http://img.b2bpic.net/free-vector/flat-design-vhs-cover-template_23-2149875857.jpg" },
                  { title: "Coming Soon", description: "Yeni projeler çok yakında.", href: "#", imageSrc: "http://img.b2bpic.net/free-vector/elegant-furniture-logo-concept_23-2148457463.jpg" },
                  { title: "Coming Soon", description: "Yeni projeler çok yakında.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/trendy-color-swatches-with-different-elements_23-2150169885.jpg" },
                  { title: "Coming Soon", description: "Yeni projeler çok yakında.", href: "#", imageSrc: "http://img.b2bpic.net/free-vector/flat-design-vhs-cover-template_23-2149913955.jpg" },
                  { title: "Coming Soon", description: "Yeni projeler çok yakında.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/plug-hybrid-electric-vehicle-combining-electric-motor-with-combustion-engine_482257-124569.jpg" }
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
